name: Build and Release
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/robot:v1.9.5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Generate RDF/XML and TTL Serializations in OWL API Style
        run: |
          robot \
            convert \
              --input om-2.0.rdf \
              --output om-2.0.ttl \
            convert \
              --format owl \
              --output om-2.0.rdf
      - name: Check DL Profile Conformance
        run: |
          robot validate-profile --profile DL --input om-2.0.ttl 1> om-2.0.dl.profile-validation.txt && {
            rm om-2.0.dl.profile-validation.txt
          } || {
            sed -i '/Profile Report:/d' om-2.0.dl.profile-validation.txt;
            sed -i '/PROFILE VIOLATION ERROR/d' om-2.0.dl.profile-validation.txt;
            sed -i '/For details see:/d' om-2.0.dl.profile-validation.txt;
            sed -i '/Use the -/d' om-2.0.dl.profile-validation.txt;
            sed -i '/^\s*$/d' om-2.0.dl.profile-validation.txt;
            sort -o om-2.0.dl.profile-validation.txt om-2.0.dl.profile-validation.txt;
            exit 1
          }
      - name: Store Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dl-profile
          path: om-2.0.*
  qlprofile:
    name: Generate and Validate QL Profile Variant
    needs: build
    runs-on: ubuntu-latest
    container: obolibrary/robot:v1.9.5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dl-profile
          path: dl-profile
      - name: Create QL Profile Compliant Variant
        run: |
          robot \
            query \
              --input dl-profile/om-2.0.ttl \
              --update scripts/om-2.0.unit-quantity-classification.ru \
            query \
              --update scripts/om-2.0.unit-prefix-classification.ru \
            convert \
              --add-prefixes scripts/om-2.0.prefixes.json \
              --output om-2.0.ql.ttl \
            convert \
              --add-prefixes scripts/om-2.0.prefixes.json \
              --format owl \
              --output om-2.0.ql.rdf
      - name: Check QL Profile Conformance
        run: |
          robot validate-profile --profile QL --input om-2.0.ql.ttl 1> om-2.0.ql.profile-validation.txt && {
            rm om-2.0.ql.profile-validation.txt
          } || {
            sed -i '/Profile Report:/d' om-2.0.ql.profile-validation.txt;
            sed -i '/PROFILE VIOLATION ERROR/d' om-2.0.ql.profile-validation.txt;
            sed -i '/For details see:/d' om-2.0.ql.profile-validation.txt;
            sed -i '/Use the -/d' om-2.0.ql.profile-validation.txt;
            sed -i '/^\s*$/d' om-2.0.ql.profile-validation.txt;
            sort -o om-2.0.ql.profile-validation.txt om-2.0.ql.profile-validation.txt;
            exit 1
          }
      - name: Store Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ql-profile
          path: om-2.0.ql.*
  elprofile:
    name: Generate and Validate EL Profile Variant
    needs: build
    runs-on: ubuntu-latest
    container: obolibrary/robot:v1.9.5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dl-profile
          path: dl-profile
      - name: Create EL Profile Compliant Variant
        run: |
          robot \
            convert \
              --input dl-profile/om-2.0.ttl \
              --add-prefixes scripts/om-2.0.prefixes.json \
              --output om-2.0.el.ttl \
            convert \
              --add-prefixes scripts/om-2.0.prefixes.json \
              --format owl \
              --output om-2.0.el.rdf
      - name: Check EL Profile Conformance
        run: |
          robot validate-profile --profile EL --input om-2.0.el.ttl 1> om-2.0.el.profile-validation.txt && {
            rm om-2.0.el.profile-validation.txt
          } || {
            sed -i '/Profile Report:/d' om-2.0.el.profile-validation.txt;
            sed -i '/PROFILE VIOLATION ERROR/d' om-2.0.el.profile-validation.txt;
            sed -i '/For details see:/d' om-2.0.el.profile-validation.txt;
            sed -i '/Use the -/d' om-2.0.el.profile-validation.txt;
            sed -i '/^\s*$/d' om-2.0.el.profile-validation.txt;
            sort -o om-2.0.el.profile-validation.txt om-2.0.el.profile-validation.txt;
            exit 1
          }
      - name: Store Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: el-profile
          path: om-2.0.el.*
  rlprofile:
    name: Generate and Validate RL Profile Variant
    needs: build
    runs-on: ubuntu-latest
    container: obolibrary/robot:v1.9.5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dl-profile
          path: dl-profile
      - name: Create RL Profile Compliant Variant
        run: |
          robot \
            convert \
              --input dl-profile/om-2.0.ttl \
              --add-prefixes scripts/om-2.0.prefixes.json \
              --output om-2.0.rl.ttl \
            convert \
              --add-prefixes scripts/om-2.0.prefixes.json \
              --format owl \
              --output om-2.0.rl.rdf
      - name: Check RL Profile Conformance
        run: |
          robot validate-profile --profile RL --input om-2.0.rl.ttl 1> om-2.0.rl.profile-validation.txt && {
            rm om-2.0.rl.profile-validation.txt
          } || {
            sed -i '/Profile Report:/d' om-2.0.rl.profile-validation.txt;
            sed -i '/PROFILE VIOLATION ERROR/d' om-2.0.rl.profile-validation.txt;
            sed -i '/For details see:/d' om-2.0.rl.profile-validation.txt;
            sed -i '/Use the -/d' om-2.0.rl.profile-validation.txt;
            sed -i '/^\s*$/d' om-2.0.rl.profile-validation.txt;
            sort -o om-2.0.rl.profile-validation.txt om-2.0.rl.profile-validation.txt;
            exit 1
          }
      - name: Store Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rl-profile
          path: om-2.0.rl.*
  profilesummary:
    name: Profile Validation Results
    needs:
      - build
      - qlprofile
      - elprofile
      - rlprofile
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dl-profile
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ql-profile
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: el-profile
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rl-profile
      - name: Generate Summary
        run: |
          printf "|Profile|Violations|Valid|\n|---|---|---|\n" >> $GITHUB_STEP_SUMMARY
          STATUS=0
          if [ -f om-2.0.dl.profile-validation.txt ]; then
            printf "|DL|$(wc -l < om-2.0.dl.profile-validation.txt)|❌|\n" >> $GITHUB_STEP_SUMMARY
            STATUS=1
          else
            printf "|DL|0|✔️|\n" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f om-2.0.ql.profile-validation.txt ]; then
            printf "|QL|$(wc -l < om-2.0.ql.profile-validation.txt)|❌|\n" >> $GITHUB_STEP_SUMMARY
            STATUS=1
          else
            printf "|QL|0|✔️|\n" >> GITHUB_STEP_SUMMARY
          fi
          if [ -f om-2.0.rl.profile-validation.txt ]; then
            printf "|RL|$(wc -l < om-2.0.rl.profile-validation.txt)|❌|\n" >> $GITHUB_STEP_SUMMARY
            STATUS=1
          else
            printf "|RL|0|✔️|\n" >> GITHUB_STEP_SUMMARY
          fi
          if [ -f om-2.0.el.profile-validation.txt ]; then
            printf "|EL|$(wc -l < om-2.0.el.profile-validation.txt)|❌|\n" >> $GITHUB_STEP_SUMMARY
            STATUS=1
          else
            printf "|EL|0|✔️|\n" >> GITHUB_STEP_SUMMARY
          fi
          exit $STATUS
  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Release Files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            om-2.0.rdf
            om-2.0.ttl